In [ ]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

In [ ]:
os.listdir()

['.config', 'drive', 'sample_data']

In [ ]:
dir = "/content/drive/MyDrive/NCCU_courses/WSM/final_project/dataset/parquet/"

In [ ]:
%%time

df_train = pd.read_parquet(dir + "train.parquet")

CPU times: user 7.14 s, sys: 5.74 s, total: 12.9 s
Wall time: 14.2 s

In [ ]:
df_train

            session      aid          ts  type
0                 0  1517085  1659304800     0
1                 0  1563459  1659304904     0
2                 0  1309446  1659367439     0
3                 0    16246  1659367719     0
4                 0  1781822  1659367871     0
...             ...      ...         ...   ...
216716091  12899776  1737908  1661723987     0
216716092  12899777   384045  1661723976     0
216716093  12899777   384045  1661723986     0
216716094  12899778   561560  1661723983     0
216716095  12899778    32070  1661723994     0

[216716096 rows x 4 columns]

In [ ]:
session_stat = {}
for session_id in tqdm(range(len(sample(train.session.unique().to_arrow().to_pylist(), 10000)))):
    session_df = train[train.session == session_id]
    n_aid = session_df.aid.nunique()
    n_ts = session_df.ts.nunique()
    n_type = session_df.type.nunique()
    session_stat[session_id] = {"n_aid": n_aid, "n_ts": n_ts, "n_type": n_type}
    break